# Generated by Django 4.2.3 on 2023-07-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_background_image_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_heading', models.CharField(max_length=100)),
                ('principal_content', models.TextField()),
                ('principal_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('our_story_heading', models.CharField(max_length=100)),
                ('our_story_content', models.TextField()),
                ('about_school_heading', models.CharField(max_length=100)),
                ('about_school_content', models.TextField()),
            ],
        ),
    ]
