# Generated by Django 4.2.3 on 2023-07-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
