# Generated by Django 4.2.3 on 2023-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
