# Generated by Django 4.2.3 on 2023-07-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
