# Generated by Django 4.2.3 on 2023-08-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_about_principal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitem',
            old_name='title',
            new_name='category',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
