# Generated by Django 4.2.3 on 2023-08-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
